# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vinoth1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8600709abaeb4b88b23bf8dd98b2ac10 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6598eca293b645859f49f41539fed4c2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8600709abaeb4b88b23bf8dd98b2ac10 }}/docker/welcome-to-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vinoth1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_985099c4a01b43a4aed76d9858cc412a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8600709abaeb4b88b23bf8dd98b2ac10 }}/docker/welcome-to-docker:${{ github.sha }}'